Repository avaire/avaire, pull requests merged in 2018-11, with the labels that each got.

#44 Add a random comic command to XKCD
  build.gradle
  src/main/java/com/avairebot/commands/search/XKCDCommand.java
  src/main/resources/langs/da_DK.yml
  src/main/resources/langs/de_DE.yml
  src/main/resources/langs/en_PT.yml
  src/main/resources/langs/en_US.yml
  src/main/resources/langs/es_ES.yml
  src/main/resources/langs/fr_FR.yml
  src/main/resources/langs/hu_HU.yml
  src/main/resources/langs/no_NB.yml
  src/main/resources/langs/ru_RU.yml
Labels: pr: low-priority, status: in progress, type: enhancement

#53 Full Heroku support for AvaIre
  .gitignore
  Procfile
  README.md
  app.json
  gradle/wrapper/gradle-wrapper.jar
Labels: pr: low-priority, status: in progress, status: need more info, type: enhancement

#51 Create a blush command
  build.gradle
  src/main/java/com/avairebot/commands/interaction/BlushCommand.java
  src/main/resources/langs/da_DK.yml
  src/main/resources/langs/de_DE.yml
  src/main/resources/langs/en_PT.yml
  src/main/resources/langs/en_US.yml
  src/main/resources/langs/es_ES.yml
  src/main/resources/langs/fr_FR.yml
  src/main/resources/langs/hu_HU.yml
  src/main/resources/langs/no_NB.yml
  src/main/resources/langs/ru_RU.yml
Labels: pr: low-priority, status: on hold, type: command

#55 Heroku last bits
  README.md
  app.json
  buildpack-run.sh
Labels: pr: low-priority, status: in progress, type: enhancement

#60 Add command to remove multiple songs from queue
  build.gradle
  src/main/java/com/avairebot/commands/music/RemoveSongFromQueueCommand.java
  src/main/resources/langs/da_DK.yml
  src/main/resources/langs/de_DE.yml
  src/main/resources/langs/en_PT.yml
  src/main/resources/langs/en_US.yml
  src/main/resources/langs/es_ES.yml
  src/main/resources/langs/fr_FR.yml
  src/main/resources/langs/hu_HU.yml
  src/main/resources/langs/no_NB.yml
  src/main/resources/langs/ru_RU.yml
Labels: pr: low-priority, status: in progress, type: command, type: enhancement
