Repository avaire/avaire, pull requests merged in 2019-02, with the labels that each got.

#76 Add ability to repeat the currently playing song
  build.gradle
  src/main/java/com/avairebot/Constants.java
  src/main/java/com/avairebot/audio/AudioTrackContainer.java
  src/main/java/com/avairebot/audio/GuildMusicManager.java
  src/main/java/com/avairebot/audio/TrackScheduler.java
  src/main/java/com/avairebot/commands/music/RemoveSongFromQueueCommand.java
  src/main/java/com/avairebot/commands/music/RepeatMusicQueueCommand.java
  src/main/java/com/avairebot/commands/music/StopCommand.java
  src/main/java/com/avairebot/contracts/audio/AudioEventWrapper.java
  src/main/java/com/avairebot/contracts/metadata/HasMetadata.java
  src/main/resources/langs/da_DK.yml
  src/main/resources/langs/de_DE.yml
  src/main/resources/langs/en_PT.yml
  src/main/resources/langs/en_US.yml
  src/main/resources/langs/es_ES.yml
  src/main/resources/langs/fr_FR.yml
  src/main/resources/langs/hu_HU.yml
  src/main/resources/langs/it_IT.yml
  src/main/resources/langs/no_NB.yml
  src/main/resources/langs/ru_RU.yml
Labels: pr: low-priority, status: in progress, type: enhancement, type: feature

#78 Added dutch language file
  build.gradle
  src/main/java/com/avairebot/language/Language.java
  src/main/resources/langs/nl_NL.yml
Labels: pr: low-priority, status: in progress, type: enhancement

#80 minor changes to en_US lang file
  src/main/resources/langs/en_US.yml
Labels: pr: low-priority, status: on hold, type: enhancement

#81 minor changes to en_US lang file 2
  src/main/resources/langs/en_US.yml
Labels: pr: low-priority, type: enhancement

#83 Adding a new Rank Background
  src/main/java/com/avairebot/imagegen/RankBackgrounds.java
  src/main/java/com/avairebot/imagegen/colors/ranks/SakuraColors.java
  src/main/resources/backgrounds/sakura.jpg
Labels: pr: low-priority, type: enhancement

#84 Added new Background
  build.gradle
  src/main/java/com/avairebot/imagegen/RankBackgrounds.java
  src/main/java/com/avairebot/imagegen/colors/ranks/EightBitMountainColors.java
  src/main/resources/backgrounds/EightBitMountains.png
Labels: pr: low-priority, type: enhancement

#77 Translated more of fr_FR.yml
  src/main/resources/langs/fr_FR.yml
Labels: pr: low-priority, status: in progress, type: enhancement
